adminUser:
  password: vault:ps-jx-cluster/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: psjxpipelinebot@gmail.com
  token: vault:ps-jx-cluster/pipelineUser:token
  username: ps-jx-pipeline-bot
prow:
  hmacToken: vault:ps-jx-cluster/prow:hmacToken
